version: '3.3'

services:
  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: aspire
      MYSQL_DATABASE: aspire
      MYSQL_USER: aspire
      MYSQL_PASSWORD: aspire
  laravel:
    depends_on:
      - db
    build:
      context: ./
    environment:
      - APP_DEBUG=true
      - APP_ENV=local
      - LOG_CHANNEL=stack
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=aspire
      - DB_USERNAME=aspire
      - DB_PASSWORD=aspire
      - CACHE_DRIVER=file
      - APP_KEY=base64:R9y0wH6KlLjMCDiQDKwmKFEZOCNEncarhttCJDgvou8=
    ports:
      - 8080:80
    volumes:
      - ./:/app
volumes:
  mysql_data: